steps:
  # 1. Install dependencies and run unit tests
  - name: 'python:3.9-slim'
    id: 'Run Unit Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest tests/

  # 2. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/sdlc-og-test/chefs-companion-repo/chefs-companion:$COMMIT_SHA', '.']

  # 3. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args: ['push', 'us-central1-docker.pkg.dev/sdlc-og-test/chefs-companion-repo/chefs-companion:$COMMIT_SHA']

  # 4. Create Cloud Deploy release to start Staging rollout
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Create Cloud Deploy Release'
    entrypoint: gcloud
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=chefs-companion'
      - '--region=us-central1'
      - '--images=app-image=us-central1-docker.pkg.dev/sdlc-og-test/chefs-companion-repo/chefs-companion:$COMMIT_SHA'

images:
  - 'us-central1-docker.pkg.dev/sdlc-og-test/chefs-companion-repo/chefs-companion:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
